version: '3.8'
services:
  dev:
    build: .
    image: franks-calendar:latest
    container_name: franks-calendar-development
    environment:
      FLASK_ENV: development
    restart: always
    tty: true
    ports:
    - "5000:5000"
    volumes:
    - ".:/www"
